### PR TITLE
Small improvements and fixes

### LINKED ISSUE #790: Polish demo code
As we just noticed on stream the demo code is a mixture of JUnit Jupiter and AssertJ assertions.
We want to align at least this (we have committed to AssertJ) , but this issue can also be used to polish other sections.

### PR DESCRIPTION
**Pull request by Michael1993**
Closes #790 

Proposed commit message:

```
${action} (${issues} / ${pull-request}) [max 70 characters]

${body} [max 70 characters per line]

${references}: ${issues}
PR: ${pull-request}
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.adoc#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Site documentation in `.adoc` file references demo in `src/demo/java` instead of containing code blocks as text
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code (general)
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [ ] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.adoc#assertions) (which are based on AssertJ)

Code (new package)
* [ ] The new package is exported in `module-info.java`
* [ ] The new package is also present in the tests
* [ ] The new package is opened for reflection to JUnit 5 in `module-info.java`
* [ ] The new package is listed in the contribution guide

Contributing
* [ ] A prepared commit message exists
* [ ] The list of contributions inside `README.adoc` mentions the new contribution (real name optional)

### CODE REVIEW

File: src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java [hunk 1]
```diff
@@ -90,8 +89,8 @@ void abortedIssueTestCaseCreated() {
 		assertThat(allTests.size()).isEqualTo(1);
 
 		IssueTestSuite issueTestSuite = allTests.get(0);
-		assertAll(() -> assertThat(issueTestSuite.issueId()).isEqualTo("#123"),
```
Comment (Bukama) [inline src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java:93]: I would not remove the sense of `assertAll` as due the removal the tests behaves different. If you want to get rid of JUnit imports in favor for AssertJ then use `Soft Asserts` (blog example here: https://eliasnogueira.com/soft-asserts-why-should-you-use-them-for-unit-and-integration-tests/ )

**Comment by Bukama** [comment]
Hey, thanks for the PR, but you know that we decided to have an issue for each PR. For me it's okay to create a "replace Junit asserts for AssertJ ones" issue, even if you do slightly more in some places.

**Comment by Michael1993** [comment]
> Hey, thanks for the PR, but you know that we decided to have an issue for each PR. For me it's okay to create a "replace Junit asserts for AssertJ ones" issue, even if you do slightly more in some places.

We have #790

**Comment by Bukama** [comment]
> > Hey, thanks for the PR, but you know that we decided to have an issue for each PR. For me it's okay to create a "replace Junit asserts for AssertJ ones" issue, even if you do slightly more in some places.
> 
> We have #790

If you would have proposed a describing message in your intro post and linked the issue I would have known ;)

I guess we can take this as a base for this PR

File: src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java (hunk 1 above)
Comment (Michael1993) [reply src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java:93]: Why do we want soft assertions here, specifically? I do not see the added benefit...?

Comment (Bukama) [reply src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java:93]: > Why do we want soft assertions here, specifically? I do not see the added benefit...?

AssertAll (JUnit) or SoftAsserts (AssertsJ equivalent) perform all asserts before failing if one fails. Without it, the tests fails at the first failure and you don't get any information about the other asserts. So it's possible that you get a failure, fix it, run test again, get next failure etc. where you could get all failures in first run.

Comment (Bukama) [reply src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java:93]: @beatngu13 Please comment with your option and treat the PR based on that. If you agree with Mihaly then feel free to merge. Otherwise request changes :D

File: build.gradle.kts [hunk 2]
```diff
@@ -310,7 +310,7 @@ tasks {
 	javadoc {
 		if (releaseBuild) {
 			javadocTool.set(project.javaToolchains.javadocToolFor {
-				// create Javadoc with least Java version to get all features
```
Comment (beatngu13) [inline build.gradle.kts:313]: "latest"?

File: build.gradle.kts [hunk 3]
```diff
@@ -342,7 +342,7 @@ tasks {
 		enabled = !experimentalBuild
 		reports {
 			xml.required.set(true)
-			xml.outputLocation.set(file("${layout.buildDirectory}/reports/jacoco/report.xml"))
```
Comment (beatngu13) [inline build.gradle.kts:345]: This is already fixed on `main`:

https://github.com/junit-pioneer/junit-pioneer/blob/main/build.gradle.kts#L339

File: src/demo/java/org/junitpioneer/jupiter/DisableIfTestFailsExtensionDemo.java [hunk 4]
```diff
@@ -38,7 +38,7 @@ void test1() {
 		@Test
 		@Order(2)
 		void test2() {
-			fail();
```
Comment (beatngu13) [inline src/demo/java/org/junitpioneer/jupiter/DisableIfTestFailsExtensionDemo.java:41]: Below you use `""`? (Too bad AssertJ has no no-arg `fails`.)

File: src/demo/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtensionDemo.java [hunk 5]
```diff
@@ -282,5 +284,13 @@ ArgumentSets provideArguments() {
 	}
 	// end::cartesian_argument_sets_with_non_static_factory[]
 
+	static class MyTestReporter implements TestReporter {
```
Comment (beatngu13) [inline src/demo/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtensionDemo.java:287]: What is this for?

File: src/test/java/org/junitpioneer/jupiter/DisableIfTestFailsTests.java [hunk 6]
```diff
@@ -10,7 +10,7 @@
 
 package org.junitpioneer.jupiter;
 
-import static org.junit.jupiter.api.Assertions.fail;
```
Comment (beatngu13) [inline src/test/java/org/junitpioneer/jupiter/DisableIfTestFailsTests.java:13]: If we want no JUpiter assertions at all, maybe ban the import ([here](https://github.com/junit-pioneer/junit-pioneer/blob/main/.infra/checkstyle/import-control.xml))?

File: src/test/java/org/junitpioneer/jupiter/ExpectedToFailExtensionTests.java [hunk 7]
```diff
@@ -42,7 +41,7 @@ void abortsOnTestFailure() {
 				.whichAborted()
 				.withExceptionInstanceOf(TestAbortedException.class)
 				.hasMessage("Test marked as temporarily 'expected to fail' failed as expected")
-				.hasCause(new AssertionFailedError("failed"));
+				.hasCause(new AssertionError("failed"));
```
Comment (beatngu13) [inline src/test/java/org/junitpioneer/jupiter/ExpectedToFailExtensionTests.java:44]: Don't we throw `AssertionFailedError` now?

File: src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java (hunk 1 above)
Comment (beatngu13) [reply src/test/java/org/junitpioneer/jupiter/issue/IssueExtensionExecutionListenerTests.java:93]: I tend to lean towards no need for `SoftAssertions` in that case, but I have no strong opinion here.

File: src/test/java/org/junitpioneer/jupiter/resource/ResourcesTests.java [hunk 8]
```diff
@@ -43,9 +37,9 @@ class WhenNewResourceFactoryAppliedToParameterTests {
 		@DisplayName("then ::create is called")
 		@Test
 		void thenCreateIsCalled() {
-			ExecutionResults executionResults = PioneerTestKit
-					.executeTestClass(CountingResourceFactory1TestCases.class);
-			assertThat(executionResults.testEvents().debug().succeeded().count()).isEqualTo(1);
+			var results = executeTestClass(CountingResourceFactory1TestCases.class);
```
Comment (beatngu13) [inline src/test/java/org/junitpioneer/jupiter/resource/ResourcesTests.java:40]: When it comes to the use of `var`, I like Snyk's [cheat sheet](https://snyk.io/de/blog/local-type-inference-java-cheat-sheet/) (written by Simon Maple and Stuart Marks).

In the given case(s), I'd either do:

```java
var executionResults = /* ... */
```

Or:

```java
ExecutionResults results = /* ... */
```

**Review by beatngu13 — COMMENTED** [review]
Thanks for the indeed small improvements! I have a few more questions (see comments).

As a small side note: various independent changes are made within a (large) commit. We also do this using when squashing PR commits, but usually alongside a meaningful commit message and an issue link. As a reviewer, I find some changes in this PR not comprehensible, at least at first sight. It would be helpful here to have smaller, atomic, and semantically coherent commits with appropriate messages. ✌️

File: src/demo/java/org/junitpioneer/jupiter/DisableIfTestFailsExtensionDemo.java (hunk 4 above)
Comment (scordio) [reply src/demo/java/org/junitpioneer/jupiter/DisableIfTestFailsExtensionDemo.java:41]: Not yet but maybe soon 😉 assertj/assertj#3204

File: build.gradle.kts (hunk 2 above)
Comment (Michael1993) [reply build.gradle.kts:313]: Actually I think this means that we use the smallest Java version we need for all the features we want to use but it's phrased a bit weird?

File: build.gradle.kts (hunk 3 above)
Comment (Michael1993) [reply build.gradle.kts:345]: Will pull.

File: src/test/java/org/junitpioneer/jupiter/ExpectedToFailExtensionTests.java (hunk 7 above)
Comment (Michael1993) [reply src/test/java/org/junitpioneer/jupiter/ExpectedToFailExtensionTests.java:44]: We do, but this is not actually us - it's AssertJ (with the `fail()` method). You could argue that checking _why_ this test failed is not necessary?

File: src/demo/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtensionDemo.java (hunk 5 above)
Comment (Michael1993) [reply src/demo/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtensionDemo.java:287]: This is for the documentation - for demonstrating an edge case with CartesianTest

File: build.gradle.kts (hunk 2 above)
Comment (beatngu13) [reply build.gradle.kts:307]: Then maybe something like:

```java
// create Javadoc with the minimum Java version needed for our desired features (e.g. search)
```

File: src/test/java/org/junitpioneer/jupiter/ExpectedToFailExtensionTests.java (hunk 7 above)
Comment (beatngu13) [reply src/test/java/org/junitpioneer/jupiter/ExpectedToFailExtensionTests.java:44]: I see, then `AssertionError` is fine I guess (also we don't use `hasCauseExactlyInstanceOf`).

**Review by beatngu13 — APPROVED** [review]
One optional comment left. Feel free to merge. ✌️
