### PR TITLE
Making SONAR happy

### LINKED ISSUE #385: Pioneer 1.1.0 fails quality gate
The current version of the expansion pack (1.1.0) failes the quality gate, because not reaching 80% (but only 75,76%) code coverage:

https://sonarcloud.io/dashboard?id=junit-pioneer_junit-pioneer

### PR DESCRIPTION
**Pull request by Michael1993**
Closes #385 

**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [ ] Tests use [AssertJ](https://joel-costigliola.github.io/assertj/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [ ] A prepared commit message exists
* [ ] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by Michael1993** [comment]
Additional bits:

* [ ] Update SONAR to not consider `equals` in test coverage
* [ ] Update SONAR to not consider `hashCode` in test coverage
* [ ] Update SONAR to not consider "record-style" getters/setters(?) in test coverage
* [ ] Update SONAR to not consider conventional getters/setters in test coverage

File: src/main/java/org/junitpioneer/jupiter/PioneerException.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+ * accompanies this distribution and is available at
+ *
+ * http://www.eclipse.org/legal/epl-v20.html
+ */
+
+package org.junitpioneer.jupiter;
+
+public class PioneerException extends RuntimeException {
+
+	public PioneerException(String s, ReflectiveOperationException ex) {
```
Comment (Michael1993) [inline src/main/java/org/junitpioneer/jupiter/PioneerException.java:15]: This was supposed to be `Exception` instead of `ReflectiveOperationException`. Oops.

File: src/test/java/org/junitpioneer/jupiter/params/PioneerAnnotationUtilsTests.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+import org.junit.jupiter.api.AfterAll;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.DisplayName;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.parallel.ResourceLock;
+import org.junitpioneer.jupiter.PioneerException;
+
+@DisplayName("Reflexive copy of PioneerAnnotationUtils")
+@ResourceLock(value = "org.junitpioneer.jupiter.params.PioneerAnnotationUtils")
```
Comment (Michael1993) [inline src/test/java/org/junitpioneer/jupiter/params/PioneerAnnotationUtilsTests.java:26]: I viscerally hate this. I don't even know why. I'm hoping someone smarter comes along and tells me a better solution.

Comment (Bukama) [reply src/test/java/org/junitpioneer/jupiter/params/PioneerAnnotationUtilsTests.java:26]: Sorry I don't. Afair the `@ResourceLock` is the way how the JUnit Jupiter guys want's you to do.

**Review by Bukama — APPROVED** [review]
Thanks
