### PR TITLE
Fix module descriptor

### LINKED ISSUE #539: Missing opens directive in module descriptor
### Problem

Using Pioneer on the module path fails with:

```text
java.lang.reflect.InaccessibleObjectException:
  Unable to make org.junitpioneer.jupiter.IssueExtension() accessible:
  module org.junitpioneer does not "opens org.junitpioneer.jupiter" to module org.junit.platform.commons
```

when using an extension located in package `org.junitpioneer.jupiter`.

### Possible Solution

Open packages that contain types using JUnit Platform's reflection support to module `org.junit.platform.commons`.

```java
  opens org.junitpioneer.jupiter to org.junit.platform.commons;
```

### Work around

Pass `--add-opens org.junitpioneer/org.junitpioneer.jupiter=org.junit.platform.commons` on the command-line or at the right place of your build tool when

### PR DESCRIPTION
**Pull request by beatngu13**
Closes #539. Follow-up #596 for proper integration tests.

Proposed commit message:

```
Fix module descriptor (#539 / #597)

This PR fixes Pioneer's `module-info.java` as follows:

* Add missing cartesian package `org.junitpioneer.jupiter.cartesian`.
* Open Pioneer packages to module `org.junit.platform.commons`, as
they contain types that use JUnit Platform's reflection support via
`PioneerAnnotationUtils`. Without the `opens` directive,
`InaccessibleObjectException`s may occur, if Pioneer is consumed on
the module path.

Closes: #539
PR: #597
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Site documentation in `.adoc` file references demo in `src/demo/java` instead of containing code blocks as text
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [ ] Code adheres to code style, naming conventions etc.
* [ ] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [ ] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [x] A prepared commit message exists
* [ ] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

File: src/main/module/module-info.java [hunk 1]
```diff
@@ -6,8 +6,13 @@
 
 	exports org.junitpioneer.vintage;
 	exports org.junitpioneer.jupiter;
+	exports org.junitpioneer.jupiter.cartesian;
 	exports org.junitpioneer.jupiter.params;
 
+	opens org.junitpioneer.jupiter to org.junit.platform.commons;
+	opens org.junitpioneer.jupiter.cartesian to org.junit.platform.commons;
+	opens org.junitpioneer.jupiter.params to org.junit.platform.commons;
```
Comment (nipafx) [inline src/main/module/module-info.java:14]: Don't we have to open `vintage` as well?

**Comment by nipafx** [comment]
I rewrote the commit message to be more specific (even if that pushes the Cartesian quick fix under the rug);

```
Open packages for reflection by JUnit (#539 / #597)

JUnit (more precisely the module `org.junit.platform.commons`)
needs to reflectively access Pioneer packages. Since some classes
aren't public, this fails with an `InaccessibleObjectException` if
Pioneer is placed on the module path. To fix this, the packages
must be opened.

Furthermore, this change fixes a mistake from #415 and exports the
new package `org.junitpioneer.jupiter.cartesian`.

Closes: #539
PR: #597
```

File: src/main/module/module-info.java (hunk 1 above)
Comment (beatngu13) [reply src/main/module/module-info.java:14]: Good point! Since `vintage` also operates on top of the Jupiter API, I will add it, too.
