### PR TITLE
Fix backup mechanism in AbstractEntryBasedExtension

### LINKED ISSUE #480: SetSystemProperty / SetEnvironmentVariable broken for nested classes
Looks like 3ecf1338f552d99a5192999ee142d09760413d78 had the side effect of breaking SetSystemProperty and SetEnvironmentVariable when used in nested classes. Example for SetSystemProperty:

```java
@SetSystemProperty(key = "PROP", value = "PROP-VALUE")
class NestedSetSystemPropertyTest {
    @Nested
    @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
    class nested {
        @Test
        @Order(1)
        void worksAsExpected() {
            assertEquals("PROP-VALUE", System.getProperty("PROP"));
        }

        @Test
        @Order(2)
        void breaksUnexpectedly() {
            assertEquals("PROP-VALUE", System.getProperty("PROP"));
        }
    }
}
```

This is due to `SystemPropertyExtension.entriesToSet()` now only returning the property "PROP" for the outermost `ExtensionContext` in `AbstractEntryBasedExtension.beforeEach()`. While this is fine during the setup phase (beforeEach/beforeAll) during tear-down `AbstractEntryBasedExtension.restoreOriginalEntries()` uses `ExtensionContext.Store.get()` to return the matching `EntriesBackup`: https://github.com/junit-pioneer/junit-pioneer/blob/3ecf1338f552d99a5192999ee142d09760413d78/src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java#L149-L151 

Note that `ExtensionContext.Store.get()` has the following [documented behaviour](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.Store.html#get(java.lang.Object,java.lang.Class)):
> If no value is stored in the current ExtensionContext for the supplied key, ancestors of the context will be queried for a value with the same key in the Namespace used to create this store.

So although the inner class and inner methods have no `EntriesBackup`, `AbstractEntryBasedExtension.restoreOriginalEntries()` grabs the outer context's instance during tear-down of `worksAsExpected()`, which accidentally clears the properties for the `breaksUnexpectedly()` test.

It would be great if `ExtensionContext.Store` were to provide a way to only query the store of the provided context and not the ancestor stores too. Haven't come up with an elegant solution for this yet. A workaround could be to store something that identifies the originating context within EntriesBackup on creation and to only restore an EntriesBackup-instance if the current context matches the originating context.

(Our workaround is to pin the junit-pioneer version to 1.4.0 for now.)

### PR DESCRIPTION
**Pull request by beatngu13**
Closes #480.

Proposed commit message:

```
Fix AbstractEntryBasedExtension backups in nested tests (#480 / #481)

`ExtensionContext$Store#get(Object)` queries ancestors of the current
context if no value is stored under the supplied key. This can mess up
backups of system properties and environment variables in nested
classes if, for instance, the current test method has no corresponding
annotation but the surrounding container. Then, the first test
execution accidentally restores the backup, which leads to incorrect
system property / environment variables settings.

This PR sidesteps this issue by ensuring that the store / backup key
is unique per test or container, respectively, by using the given
display name.

Closes: #480
PR: #481
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [x] Code adheres to code style, naming conventions etc.
* [x] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [x] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [x] A prepared commit message exists
* [x] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

**Comment by Michael1993** [comment]
Wouldn't it be simpler to only use `BeforeEachCallback` and `AfterEachCallback`?

**Comment by beatngu13** [comment]
@Michael1993 as described in #460, this would require some bigger changes in the extension(s) such as preserving the order of entries to clear and set. I already have a stash locally for that, but I would like to separate refactoring from fixing this regression, if that is OK for you.

File: src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java [hunk 1]
```diff
@@ -147,18 +138,26 @@ public void afterAll(ExtensionContext context) throws Exception {
...
-		getStore(context).get(BACKUP, EntriesBackup.class).restoreBackup();
+		getStore(context).getOrDefault(getStoreKey(context), EntriesBackup.class, new EntriesBackup()).restoreBackup();
 	}
 
 	private Store getStore(ExtensionContext context) {
 		return context.getStore(Namespace.create(getClass()));
 	}
 
+	private Object getStoreKey(ExtensionContext context) {
+		return context.getDisplayName();
```
Comment (Bukama) [inline src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java:149]: The `Displayname` is *NOT* unique! this can lead to further collisions!
But each test (and container) has an uniqueid. I think this is the more safer way.

File: src/test/java/org/junitpioneer/jupiter/AbstractEntryBasedExtensionTest.java [hunk 2]
```diff
@@ -38,6 +38,7 @@ void setUp() {
 	}
 
 	@Test
+	@Issue("432")
```
Comment (Bukama) [inline src/test/java/org/junitpioneer/jupiter/AbstractEntryBasedExtensionTest.java:41]: <3

**Review by Bukama — CHANGES_REQUESTED** [review]
I set this to "request changes" because I see further conflict potential we should look into and see if there's s a "safer" way. Meaning if we can access the unique Id of a test at the point where you get the displayname at the moment.

File: src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java (hunk 1 above)
Comment (beatngu13) [reply src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java]: Good point, switched to [`ExtensionContext#getUniqueId()`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.html#getUniqueId()).

File: src/test/java/org/junitpioneer/jupiter/AbstractEntryBasedExtensionTest.java (hunk 2 above)
Comment (beatngu13) [reply src/test/java/org/junitpioneer/jupiter/AbstractEntryBasedExtensionTest.java:41]: Wonder why we didn't use it before, so helpful! 👏

**Review by Michael1993 — COMMENTED** [review]
I don't know enough about this extension to approve this now.

**Review by Bukama — APPROVED** [review]
Thanks for changing. We should be safe with the uniqueID. 👍
