### PR TITLE
Fix SetEnvironmentVariable and SetSystemProperty interference

### LINKED ISSUE #432: SetEnvironmentVariable and SetSystemProperty interfere
When `@SetEnvironmentVariable` and `@SetSystemProperty` are used on the same test, only one set of properties is restored at the end of the test.

It looks like they both use `AbstractEntryBasedExtension` and that will overwrite the `EntriesBackup` for the first annotation when the second annotation is processed since it's stored in the same place in the context.

I think either the namespace or the key used to store the backup in the context needs to be derived from the implementing class.

### PR DESCRIPTION
**Pull request by beatngu13**
Closes #432.

Proposed commit message:

```
Create namespace per entry-based extension (#432 / #433)

Instead of creating a single namespace based on
`AbstractEntryBasedExtension.class` for all entry-based extensions,
using `getClass()` ensures per-extension namespaces via the runtime
class (i.e. the actual extension).

Closes: #432
PR: #433
```

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [ ] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [ ] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [ ] Only one sentence per line (especially in `.adoc` files)
* [ ] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [ ] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [ ] The `package-info.java` contains information about the new extension

Code
* [x] Code adheres to code style, naming conventions etc.
* [x] Successful tests cover all changes
* [ ] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [x] Tests use [AssertJ](https://joel-costigliola.github.io/assertj/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [x] A prepared commit message exists
* [x] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/master/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

### CODE REVIEW

File: src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java [hunk 1]
```diff
@@ -147,7 +147,11 @@ public void afterAll(ExtensionContext context) throws Exception {
 	}
 
 	private void restoreOriginalEntries(ExtensionContext context) {
-		context.getStore(NAMESPACE).get(BACKUP, EntriesBackup.class).restoreBackup();
+		getStore(context).get(BACKUP, EntriesBackup.class).restoreBackup();
+	}
+
+	private Store getStore(ExtensionContext context) {
+		return context.getStore(Namespace.create(getClass()));
```
Comment (Michael1993) [inline src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java:154]: Always creates a new `Namespace`?

Comment (Michael1993) [reply src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java:154]: Consider the following solution:
```java
protected abstract Namespace namespace();
```
which in turn gets turned into
```java
private static final Namespace NAMESPACE = Namespace.create(...);

@Override
protected Namespace namespace() {
  return NAMESPACE;
}
```
Is that too complex?

**Review by Michael1993 — COMMENTED** [review]
It looks good to me, but I do have a question.

File: src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java (hunk 1 above)
Comment (beatngu13) [reply src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java:154]: I borrowed this from JUnit's `TimingExtension` [example](https://junit.org/junit5/docs/current/user-guide/#extensions-lifecycle-callbacks-timing-extension). It may not be ideal, but I'm not sure if it's worth to further blow up the base class -- we already have 6 `abstract` methods.

Alternatively, we could also set it in the abstract ctor. Something like:

```java
abstract class AbstractEntryBasedExtension {

    private final Namespace namespace;

    protected AbstractEntryBasedExtension() {
        this.namespace = Namespace.create(getClass());
    }

}
```

What do you prefer? Keep it as it is, additional `abstract` method, abstract ctor, ...?

Comment (Michael1993) [reply src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java:154]: It doesn't really matter, it's a very minor thing.

Comment (Michael1993) [reply src/main/java/org/junitpioneer/jupiter/AbstractEntryBasedExtension.java:154]: Out of all the possible solution, yours is probably the easiest to understand (it's all in one place) and it shouldn't impact performance. Let's leave it as it is.

**Review by Michael1993 — APPROVED** [review]
LGTM

**Review by Azquelt — APPROVED** [review]
This change looks good to me and I have confirmed it fixes the issue I was seeing. Thanks :smile:

**Review by Bukama — APPROVED** [review]
LGTM :)
